services:

  exercise2-2:
    image: devopsdockeruh/simple-web-service
    build: .
    volumes:
      - ./text.log:/usr/src/app/text.log
    ports:
      - 127.0.0.1:8080:8080
    container_name: exercise2-2
    command: server
