FROM node:16

WORKDIR /usr/src/app

COPY . ./

ENV REACT_APP_BACKEND_URL=http://localhost:8080

RUN npm install && npm run build && npm install -g serve

RUN useradd -m appuser

RUN chown appuser .

USER appuser

EXPOSE 5000

CMD serve -s -l 5000 build
