name: Release Node.js app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: ./part1/exercise1_15
        push: true
        tags: mashiahoz/exercise1-15:latest

    - name: deploy new image on render cloud
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
        api-key: ${{ secrets.MY_RENDER_API_KEY }}
        wait-for-success: true
